id = "easy-opaque-theme"
name = "Easy Opaque"
version = "0.0.1"
schema_version = 1
authors = ["kargency@gmail.com"]
description = "Easy to read, no gray-on-white fonts, red highlights."
repository = "https://github.com/KarmanyaIyer/zed-easy-opaque-theme"
